name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, ubuntu-16.04]
    
    steps:
    - uses: actions/checkout@v1
    - name: Run unit tests
      run: |
        docker build --tag ${GITHUB_REPOSITORY} .
        docker run ${GITHUB_REPOSITORY}
    - name: Build release modes
      run: echo "We should implement this"
